// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/task_service.proto

#include "proto/task_service.pb.h"
#include "proto/task_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace taskservice {

static const char* TaskExecutor_method_names[] = {
  "/taskservice.TaskExecutor/ExecuteTaskAsync",
  "/taskservice.TaskExecutor/ExecuteTask",
};

std::unique_ptr< TaskExecutor::Stub> TaskExecutor::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TaskExecutor::Stub> stub(new TaskExecutor::Stub(channel, options));
  return stub;
}

TaskExecutor::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ExecuteTaskAsync_(TaskExecutor_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ExecuteTask_(TaskExecutor_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::ClientReader< ::taskservice::TaskResponse>* TaskExecutor::Stub::ExecuteTaskAsyncRaw(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::taskservice::TaskResponse>::Create(channel_.get(), rpcmethod_ExecuteTaskAsync_, context, request);
}

void TaskExecutor::Stub::async::ExecuteTaskAsync(::grpc::ClientContext* context, const ::taskservice::TaskRequest* request, ::grpc::ClientReadReactor< ::taskservice::TaskResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::taskservice::TaskResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_ExecuteTaskAsync_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::taskservice::TaskResponse>* TaskExecutor::Stub::AsyncExecuteTaskAsyncRaw(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::taskservice::TaskResponse>::Create(channel_.get(), cq, rpcmethod_ExecuteTaskAsync_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::taskservice::TaskResponse>* TaskExecutor::Stub::PrepareAsyncExecuteTaskAsyncRaw(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::taskservice::TaskResponse>::Create(channel_.get(), cq, rpcmethod_ExecuteTaskAsync_, context, request, false, nullptr);
}

::grpc::Status TaskExecutor::Stub::ExecuteTask(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::taskservice::TaskResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::taskservice::TaskRequest, ::taskservice::TaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExecuteTask_, context, request, response);
}

void TaskExecutor::Stub::async::ExecuteTask(::grpc::ClientContext* context, const ::taskservice::TaskRequest* request, ::taskservice::TaskResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::taskservice::TaskRequest, ::taskservice::TaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteTask_, context, request, response, std::move(f));
}

void TaskExecutor::Stub::async::ExecuteTask(::grpc::ClientContext* context, const ::taskservice::TaskRequest* request, ::taskservice::TaskResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteTask_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::taskservice::TaskResponse>* TaskExecutor::Stub::PrepareAsyncExecuteTaskRaw(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::taskservice::TaskResponse, ::taskservice::TaskRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExecuteTask_, context, request);
}

::grpc::ClientAsyncResponseReader< ::taskservice::TaskResponse>* TaskExecutor::Stub::AsyncExecuteTaskRaw(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteTaskRaw(context, request, cq);
  result->StartCall();
  return result;
}

TaskExecutor::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TaskExecutor_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< TaskExecutor::Service, ::taskservice::TaskRequest, ::taskservice::TaskResponse>(
          [](TaskExecutor::Service* service,
             ::grpc::ServerContext* ctx,
             const ::taskservice::TaskRequest* req,
             ::grpc::ServerWriter<::taskservice::TaskResponse>* writer) {
               return service->ExecuteTaskAsync(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TaskExecutor_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TaskExecutor::Service, ::taskservice::TaskRequest, ::taskservice::TaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TaskExecutor::Service* service,
             ::grpc::ServerContext* ctx,
             const ::taskservice::TaskRequest* req,
             ::taskservice::TaskResponse* resp) {
               return service->ExecuteTask(ctx, req, resp);
             }, this)));
}

TaskExecutor::Service::~Service() {
}

::grpc::Status TaskExecutor::Service::ExecuteTaskAsync(::grpc::ServerContext* context, const ::taskservice::TaskRequest* request, ::grpc::ServerWriter< ::taskservice::TaskResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TaskExecutor::Service::ExecuteTask(::grpc::ServerContext* context, const ::taskservice::TaskRequest* request, ::taskservice::TaskResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace taskservice

