// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/task_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2ftask_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2ftask_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2ftask_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2ftask_5fservice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2ftask_5fservice_2eproto;
namespace taskservice {
class TaskRequest;
struct TaskRequestDefaultTypeInternal;
extern TaskRequestDefaultTypeInternal _TaskRequest_default_instance_;
class TaskResponse;
struct TaskResponseDefaultTypeInternal;
extern TaskResponseDefaultTypeInternal _TaskResponse_default_instance_;
}  // namespace taskservice
PROTOBUF_NAMESPACE_OPEN
template<> ::taskservice::TaskRequest* Arena::CreateMaybeMessage<::taskservice::TaskRequest>(Arena*);
template<> ::taskservice::TaskResponse* Arena::CreateMaybeMessage<::taskservice::TaskResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace taskservice {

// ===================================================================

class TaskRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:taskservice.TaskRequest) */ {
 public:
  inline TaskRequest() : TaskRequest(nullptr) {}
  ~TaskRequest() override;
  explicit PROTOBUF_CONSTEXPR TaskRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TaskRequest(const TaskRequest& from);
  TaskRequest(TaskRequest&& from) noexcept
    : TaskRequest() {
    *this = ::std::move(from);
  }

  inline TaskRequest& operator=(const TaskRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaskRequest& operator=(TaskRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TaskRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const TaskRequest* internal_default_instance() {
    return reinterpret_cast<const TaskRequest*>(
               &_TaskRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TaskRequest& a, TaskRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(TaskRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaskRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TaskRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TaskRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TaskRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TaskRequest& from) {
    TaskRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TaskRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "taskservice.TaskRequest";
  }
  protected:
  explicit TaskRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTaskNameFieldNumber = 2,
    kInputsJsonFieldNumber = 3,
    kPolicyFieldNumber = 5,
    kTaskIdFieldNumber = 1,
    kPriorityFieldNumber = 4,
  };
  // string task_name = 2;
  void clear_task_name();
  const std::string& task_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_task_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_task_name();
  PROTOBUF_NODISCARD std::string* release_task_name();
  void set_allocated_task_name(std::string* task_name);
  private:
  const std::string& _internal_task_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_task_name(const std::string& value);
  std::string* _internal_mutable_task_name();
  public:

  // string inputs_json = 3;
  void clear_inputs_json();
  const std::string& inputs_json() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_inputs_json(ArgT0&& arg0, ArgT... args);
  std::string* mutable_inputs_json();
  PROTOBUF_NODISCARD std::string* release_inputs_json();
  void set_allocated_inputs_json(std::string* inputs_json);
  private:
  const std::string& _internal_inputs_json() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_inputs_json(const std::string& value);
  std::string* _internal_mutable_inputs_json();
  public:

  // string policy = 5;
  void clear_policy();
  const std::string& policy() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_policy(ArgT0&& arg0, ArgT... args);
  std::string* mutable_policy();
  PROTOBUF_NODISCARD std::string* release_policy();
  void set_allocated_policy(std::string* policy);
  private:
  const std::string& _internal_policy() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_policy(const std::string& value);
  std::string* _internal_mutable_policy();
  public:

  // uint32 task_id = 1;
  void clear_task_id();
  uint32_t task_id() const;
  void set_task_id(uint32_t value);
  private:
  uint32_t _internal_task_id() const;
  void _internal_set_task_id(uint32_t value);
  public:

  // int32 priority = 4;
  void clear_priority();
  int32_t priority() const;
  void set_priority(int32_t value);
  private:
  int32_t _internal_priority() const;
  void _internal_set_priority(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:taskservice.TaskRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr task_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr inputs_json_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr policy_;
    uint32_t task_id_;
    int32_t priority_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2ftask_5fservice_2eproto;
};
// -------------------------------------------------------------------

class TaskResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:taskservice.TaskResponse) */ {
 public:
  inline TaskResponse() : TaskResponse(nullptr) {}
  ~TaskResponse() override;
  explicit PROTOBUF_CONSTEXPR TaskResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TaskResponse(const TaskResponse& from);
  TaskResponse(TaskResponse&& from) noexcept
    : TaskResponse() {
    *this = ::std::move(from);
  }

  inline TaskResponse& operator=(const TaskResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaskResponse& operator=(TaskResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TaskResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const TaskResponse* internal_default_instance() {
    return reinterpret_cast<const TaskResponse*>(
               &_TaskResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TaskResponse& a, TaskResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(TaskResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaskResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TaskResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TaskResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TaskResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TaskResponse& from) {
    TaskResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TaskResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "taskservice.TaskResponse";
  }
  protected:
  explicit TaskResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 2,
    kResultJsonFieldNumber = 3,
    kErrorMessageFieldNumber = 4,
    kTaskIdFieldNumber = 1,
  };
  // string status = 2;
  void clear_status();
  const std::string& status() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_status(ArgT0&& arg0, ArgT... args);
  std::string* mutable_status();
  PROTOBUF_NODISCARD std::string* release_status();
  void set_allocated_status(std::string* status);
  private:
  const std::string& _internal_status() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_status(const std::string& value);
  std::string* _internal_mutable_status();
  public:

  // string result_json = 3;
  void clear_result_json();
  const std::string& result_json() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_result_json(ArgT0&& arg0, ArgT... args);
  std::string* mutable_result_json();
  PROTOBUF_NODISCARD std::string* release_result_json();
  void set_allocated_result_json(std::string* result_json);
  private:
  const std::string& _internal_result_json() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_result_json(const std::string& value);
  std::string* _internal_mutable_result_json();
  public:

  // string error_message = 4;
  void clear_error_message();
  const std::string& error_message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // uint32 task_id = 1;
  void clear_task_id();
  uint32_t task_id() const;
  void set_task_id(uint32_t value);
  private:
  uint32_t _internal_task_id() const;
  void _internal_set_task_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:taskservice.TaskResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr result_json_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
    uint32_t task_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2ftask_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TaskRequest

// uint32 task_id = 1;
inline void TaskRequest::clear_task_id() {
  _impl_.task_id_ = 0u;
}
inline uint32_t TaskRequest::_internal_task_id() const {
  return _impl_.task_id_;
}
inline uint32_t TaskRequest::task_id() const {
  // @@protoc_insertion_point(field_get:taskservice.TaskRequest.task_id)
  return _internal_task_id();
}
inline void TaskRequest::_internal_set_task_id(uint32_t value) {
  
  _impl_.task_id_ = value;
}
inline void TaskRequest::set_task_id(uint32_t value) {
  _internal_set_task_id(value);
  // @@protoc_insertion_point(field_set:taskservice.TaskRequest.task_id)
}

// string task_name = 2;
inline void TaskRequest::clear_task_name() {
  _impl_.task_name_.ClearToEmpty();
}
inline const std::string& TaskRequest::task_name() const {
  // @@protoc_insertion_point(field_get:taskservice.TaskRequest.task_name)
  return _internal_task_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TaskRequest::set_task_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.task_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:taskservice.TaskRequest.task_name)
}
inline std::string* TaskRequest::mutable_task_name() {
  std::string* _s = _internal_mutable_task_name();
  // @@protoc_insertion_point(field_mutable:taskservice.TaskRequest.task_name)
  return _s;
}
inline const std::string& TaskRequest::_internal_task_name() const {
  return _impl_.task_name_.Get();
}
inline void TaskRequest::_internal_set_task_name(const std::string& value) {
  
  _impl_.task_name_.Set(value, GetArenaForAllocation());
}
inline std::string* TaskRequest::_internal_mutable_task_name() {
  
  return _impl_.task_name_.Mutable(GetArenaForAllocation());
}
inline std::string* TaskRequest::release_task_name() {
  // @@protoc_insertion_point(field_release:taskservice.TaskRequest.task_name)
  return _impl_.task_name_.Release();
}
inline void TaskRequest::set_allocated_task_name(std::string* task_name) {
  if (task_name != nullptr) {
    
  } else {
    
  }
  _impl_.task_name_.SetAllocated(task_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.task_name_.IsDefault()) {
    _impl_.task_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:taskservice.TaskRequest.task_name)
}

// string inputs_json = 3;
inline void TaskRequest::clear_inputs_json() {
  _impl_.inputs_json_.ClearToEmpty();
}
inline const std::string& TaskRequest::inputs_json() const {
  // @@protoc_insertion_point(field_get:taskservice.TaskRequest.inputs_json)
  return _internal_inputs_json();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TaskRequest::set_inputs_json(ArgT0&& arg0, ArgT... args) {
 
 _impl_.inputs_json_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:taskservice.TaskRequest.inputs_json)
}
inline std::string* TaskRequest::mutable_inputs_json() {
  std::string* _s = _internal_mutable_inputs_json();
  // @@protoc_insertion_point(field_mutable:taskservice.TaskRequest.inputs_json)
  return _s;
}
inline const std::string& TaskRequest::_internal_inputs_json() const {
  return _impl_.inputs_json_.Get();
}
inline void TaskRequest::_internal_set_inputs_json(const std::string& value) {
  
  _impl_.inputs_json_.Set(value, GetArenaForAllocation());
}
inline std::string* TaskRequest::_internal_mutable_inputs_json() {
  
  return _impl_.inputs_json_.Mutable(GetArenaForAllocation());
}
inline std::string* TaskRequest::release_inputs_json() {
  // @@protoc_insertion_point(field_release:taskservice.TaskRequest.inputs_json)
  return _impl_.inputs_json_.Release();
}
inline void TaskRequest::set_allocated_inputs_json(std::string* inputs_json) {
  if (inputs_json != nullptr) {
    
  } else {
    
  }
  _impl_.inputs_json_.SetAllocated(inputs_json, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.inputs_json_.IsDefault()) {
    _impl_.inputs_json_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:taskservice.TaskRequest.inputs_json)
}

// int32 priority = 4;
inline void TaskRequest::clear_priority() {
  _impl_.priority_ = 0;
}
inline int32_t TaskRequest::_internal_priority() const {
  return _impl_.priority_;
}
inline int32_t TaskRequest::priority() const {
  // @@protoc_insertion_point(field_get:taskservice.TaskRequest.priority)
  return _internal_priority();
}
inline void TaskRequest::_internal_set_priority(int32_t value) {
  
  _impl_.priority_ = value;
}
inline void TaskRequest::set_priority(int32_t value) {
  _internal_set_priority(value);
  // @@protoc_insertion_point(field_set:taskservice.TaskRequest.priority)
}

// string policy = 5;
inline void TaskRequest::clear_policy() {
  _impl_.policy_.ClearToEmpty();
}
inline const std::string& TaskRequest::policy() const {
  // @@protoc_insertion_point(field_get:taskservice.TaskRequest.policy)
  return _internal_policy();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TaskRequest::set_policy(ArgT0&& arg0, ArgT... args) {
 
 _impl_.policy_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:taskservice.TaskRequest.policy)
}
inline std::string* TaskRequest::mutable_policy() {
  std::string* _s = _internal_mutable_policy();
  // @@protoc_insertion_point(field_mutable:taskservice.TaskRequest.policy)
  return _s;
}
inline const std::string& TaskRequest::_internal_policy() const {
  return _impl_.policy_.Get();
}
inline void TaskRequest::_internal_set_policy(const std::string& value) {
  
  _impl_.policy_.Set(value, GetArenaForAllocation());
}
inline std::string* TaskRequest::_internal_mutable_policy() {
  
  return _impl_.policy_.Mutable(GetArenaForAllocation());
}
inline std::string* TaskRequest::release_policy() {
  // @@protoc_insertion_point(field_release:taskservice.TaskRequest.policy)
  return _impl_.policy_.Release();
}
inline void TaskRequest::set_allocated_policy(std::string* policy) {
  if (policy != nullptr) {
    
  } else {
    
  }
  _impl_.policy_.SetAllocated(policy, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.policy_.IsDefault()) {
    _impl_.policy_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:taskservice.TaskRequest.policy)
}

// -------------------------------------------------------------------

// TaskResponse

// uint32 task_id = 1;
inline void TaskResponse::clear_task_id() {
  _impl_.task_id_ = 0u;
}
inline uint32_t TaskResponse::_internal_task_id() const {
  return _impl_.task_id_;
}
inline uint32_t TaskResponse::task_id() const {
  // @@protoc_insertion_point(field_get:taskservice.TaskResponse.task_id)
  return _internal_task_id();
}
inline void TaskResponse::_internal_set_task_id(uint32_t value) {
  
  _impl_.task_id_ = value;
}
inline void TaskResponse::set_task_id(uint32_t value) {
  _internal_set_task_id(value);
  // @@protoc_insertion_point(field_set:taskservice.TaskResponse.task_id)
}

// string status = 2;
inline void TaskResponse::clear_status() {
  _impl_.status_.ClearToEmpty();
}
inline const std::string& TaskResponse::status() const {
  // @@protoc_insertion_point(field_get:taskservice.TaskResponse.status)
  return _internal_status();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TaskResponse::set_status(ArgT0&& arg0, ArgT... args) {
 
 _impl_.status_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:taskservice.TaskResponse.status)
}
inline std::string* TaskResponse::mutable_status() {
  std::string* _s = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:taskservice.TaskResponse.status)
  return _s;
}
inline const std::string& TaskResponse::_internal_status() const {
  return _impl_.status_.Get();
}
inline void TaskResponse::_internal_set_status(const std::string& value) {
  
  _impl_.status_.Set(value, GetArenaForAllocation());
}
inline std::string* TaskResponse::_internal_mutable_status() {
  
  return _impl_.status_.Mutable(GetArenaForAllocation());
}
inline std::string* TaskResponse::release_status() {
  // @@protoc_insertion_point(field_release:taskservice.TaskResponse.status)
  return _impl_.status_.Release();
}
inline void TaskResponse::set_allocated_status(std::string* status) {
  if (status != nullptr) {
    
  } else {
    
  }
  _impl_.status_.SetAllocated(status, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.status_.IsDefault()) {
    _impl_.status_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:taskservice.TaskResponse.status)
}

// string result_json = 3;
inline void TaskResponse::clear_result_json() {
  _impl_.result_json_.ClearToEmpty();
}
inline const std::string& TaskResponse::result_json() const {
  // @@protoc_insertion_point(field_get:taskservice.TaskResponse.result_json)
  return _internal_result_json();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TaskResponse::set_result_json(ArgT0&& arg0, ArgT... args) {
 
 _impl_.result_json_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:taskservice.TaskResponse.result_json)
}
inline std::string* TaskResponse::mutable_result_json() {
  std::string* _s = _internal_mutable_result_json();
  // @@protoc_insertion_point(field_mutable:taskservice.TaskResponse.result_json)
  return _s;
}
inline const std::string& TaskResponse::_internal_result_json() const {
  return _impl_.result_json_.Get();
}
inline void TaskResponse::_internal_set_result_json(const std::string& value) {
  
  _impl_.result_json_.Set(value, GetArenaForAllocation());
}
inline std::string* TaskResponse::_internal_mutable_result_json() {
  
  return _impl_.result_json_.Mutable(GetArenaForAllocation());
}
inline std::string* TaskResponse::release_result_json() {
  // @@protoc_insertion_point(field_release:taskservice.TaskResponse.result_json)
  return _impl_.result_json_.Release();
}
inline void TaskResponse::set_allocated_result_json(std::string* result_json) {
  if (result_json != nullptr) {
    
  } else {
    
  }
  _impl_.result_json_.SetAllocated(result_json, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.result_json_.IsDefault()) {
    _impl_.result_json_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:taskservice.TaskResponse.result_json)
}

// string error_message = 4;
inline void TaskResponse::clear_error_message() {
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& TaskResponse::error_message() const {
  // @@protoc_insertion_point(field_get:taskservice.TaskResponse.error_message)
  return _internal_error_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TaskResponse::set_error_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:taskservice.TaskResponse.error_message)
}
inline std::string* TaskResponse::mutable_error_message() {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:taskservice.TaskResponse.error_message)
  return _s;
}
inline const std::string& TaskResponse::_internal_error_message() const {
  return _impl_.error_message_.Get();
}
inline void TaskResponse::_internal_set_error_message(const std::string& value) {
  
  _impl_.error_message_.Set(value, GetArenaForAllocation());
}
inline std::string* TaskResponse::_internal_mutable_error_message() {
  
  return _impl_.error_message_.Mutable(GetArenaForAllocation());
}
inline std::string* TaskResponse::release_error_message() {
  // @@protoc_insertion_point(field_release:taskservice.TaskResponse.error_message)
  return _impl_.error_message_.Release();
}
inline void TaskResponse::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  _impl_.error_message_.SetAllocated(error_message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:taskservice.TaskResponse.error_message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace taskservice

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2ftask_5fservice_2eproto
