// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/task_service.proto
#ifndef GRPC_proto_2ftask_5fservice_2eproto__INCLUDED
#define GRPC_proto_2ftask_5fservice_2eproto__INCLUDED

#include "proto/task_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace taskservice {

// Service definition
class TaskExecutor final {
 public:
  static constexpr char const* service_full_name() {
    return "taskservice.TaskExecutor";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Execute a task asynchronously with streaming responses
    // First response: ACK (task started)
    // Second response: RESULT (task completed)
    std::unique_ptr< ::grpc::ClientReaderInterface< ::taskservice::TaskResponse>> ExecuteTaskAsync(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::taskservice::TaskResponse>>(ExecuteTaskAsyncRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::taskservice::TaskResponse>> AsyncExecuteTaskAsync(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::taskservice::TaskResponse>>(AsyncExecuteTaskAsyncRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::taskservice::TaskResponse>> PrepareAsyncExecuteTaskAsync(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::taskservice::TaskResponse>>(PrepareAsyncExecuteTaskAsyncRaw(context, request, cq));
    }
    // Legacy synchronous method (kept for compatibility)
    virtual ::grpc::Status ExecuteTask(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::taskservice::TaskResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::taskservice::TaskResponse>> AsyncExecuteTask(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::taskservice::TaskResponse>>(AsyncExecuteTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::taskservice::TaskResponse>> PrepareAsyncExecuteTask(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::taskservice::TaskResponse>>(PrepareAsyncExecuteTaskRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Execute a task asynchronously with streaming responses
      // First response: ACK (task started)
      // Second response: RESULT (task completed)
      virtual void ExecuteTaskAsync(::grpc::ClientContext* context, const ::taskservice::TaskRequest* request, ::grpc::ClientReadReactor< ::taskservice::TaskResponse>* reactor) = 0;
      // Legacy synchronous method (kept for compatibility)
      virtual void ExecuteTask(::grpc::ClientContext* context, const ::taskservice::TaskRequest* request, ::taskservice::TaskResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ExecuteTask(::grpc::ClientContext* context, const ::taskservice::TaskRequest* request, ::taskservice::TaskResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::taskservice::TaskResponse>* ExecuteTaskAsyncRaw(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::taskservice::TaskResponse>* AsyncExecuteTaskAsyncRaw(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::taskservice::TaskResponse>* PrepareAsyncExecuteTaskAsyncRaw(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::taskservice::TaskResponse>* AsyncExecuteTaskRaw(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::taskservice::TaskResponse>* PrepareAsyncExecuteTaskRaw(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::taskservice::TaskResponse>> ExecuteTaskAsync(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::taskservice::TaskResponse>>(ExecuteTaskAsyncRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::taskservice::TaskResponse>> AsyncExecuteTaskAsync(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::taskservice::TaskResponse>>(AsyncExecuteTaskAsyncRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::taskservice::TaskResponse>> PrepareAsyncExecuteTaskAsync(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::taskservice::TaskResponse>>(PrepareAsyncExecuteTaskAsyncRaw(context, request, cq));
    }
    ::grpc::Status ExecuteTask(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::taskservice::TaskResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::taskservice::TaskResponse>> AsyncExecuteTask(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::taskservice::TaskResponse>>(AsyncExecuteTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::taskservice::TaskResponse>> PrepareAsyncExecuteTask(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::taskservice::TaskResponse>>(PrepareAsyncExecuteTaskRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ExecuteTaskAsync(::grpc::ClientContext* context, const ::taskservice::TaskRequest* request, ::grpc::ClientReadReactor< ::taskservice::TaskResponse>* reactor) override;
      void ExecuteTask(::grpc::ClientContext* context, const ::taskservice::TaskRequest* request, ::taskservice::TaskResponse* response, std::function<void(::grpc::Status)>) override;
      void ExecuteTask(::grpc::ClientContext* context, const ::taskservice::TaskRequest* request, ::taskservice::TaskResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::taskservice::TaskResponse>* ExecuteTaskAsyncRaw(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request) override;
    ::grpc::ClientAsyncReader< ::taskservice::TaskResponse>* AsyncExecuteTaskAsyncRaw(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::taskservice::TaskResponse>* PrepareAsyncExecuteTaskAsyncRaw(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::taskservice::TaskResponse>* AsyncExecuteTaskRaw(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::taskservice::TaskResponse>* PrepareAsyncExecuteTaskRaw(::grpc::ClientContext* context, const ::taskservice::TaskRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ExecuteTaskAsync_;
    const ::grpc::internal::RpcMethod rpcmethod_ExecuteTask_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Execute a task asynchronously with streaming responses
    // First response: ACK (task started)
    // Second response: RESULT (task completed)
    virtual ::grpc::Status ExecuteTaskAsync(::grpc::ServerContext* context, const ::taskservice::TaskRequest* request, ::grpc::ServerWriter< ::taskservice::TaskResponse>* writer);
    // Legacy synchronous method (kept for compatibility)
    virtual ::grpc::Status ExecuteTask(::grpc::ServerContext* context, const ::taskservice::TaskRequest* request, ::taskservice::TaskResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ExecuteTaskAsync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ExecuteTaskAsync() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ExecuteTaskAsync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTaskAsync(::grpc::ServerContext* /*context*/, const ::taskservice::TaskRequest* /*request*/, ::grpc::ServerWriter< ::taskservice::TaskResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteTaskAsync(::grpc::ServerContext* context, ::taskservice::TaskRequest* request, ::grpc::ServerAsyncWriter< ::taskservice::TaskResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ExecuteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ExecuteTask() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ExecuteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTask(::grpc::ServerContext* /*context*/, const ::taskservice::TaskRequest* /*request*/, ::taskservice::TaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteTask(::grpc::ServerContext* context, ::taskservice::TaskRequest* request, ::grpc::ServerAsyncResponseWriter< ::taskservice::TaskResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ExecuteTaskAsync<WithAsyncMethod_ExecuteTask<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ExecuteTaskAsync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ExecuteTaskAsync() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::taskservice::TaskRequest, ::taskservice::TaskResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::taskservice::TaskRequest* request) { return this->ExecuteTaskAsync(context, request); }));
    }
    ~WithCallbackMethod_ExecuteTaskAsync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTaskAsync(::grpc::ServerContext* /*context*/, const ::taskservice::TaskRequest* /*request*/, ::grpc::ServerWriter< ::taskservice::TaskResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::taskservice::TaskResponse>* ExecuteTaskAsync(
      ::grpc::CallbackServerContext* /*context*/, const ::taskservice::TaskRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ExecuteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ExecuteTask() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::taskservice::TaskRequest, ::taskservice::TaskResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::taskservice::TaskRequest* request, ::taskservice::TaskResponse* response) { return this->ExecuteTask(context, request, response); }));}
    void SetMessageAllocatorFor_ExecuteTask(
        ::grpc::MessageAllocator< ::taskservice::TaskRequest, ::taskservice::TaskResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::taskservice::TaskRequest, ::taskservice::TaskResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ExecuteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTask(::grpc::ServerContext* /*context*/, const ::taskservice::TaskRequest* /*request*/, ::taskservice::TaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExecuteTask(
      ::grpc::CallbackServerContext* /*context*/, const ::taskservice::TaskRequest* /*request*/, ::taskservice::TaskResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ExecuteTaskAsync<WithCallbackMethod_ExecuteTask<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ExecuteTaskAsync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ExecuteTaskAsync() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ExecuteTaskAsync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTaskAsync(::grpc::ServerContext* /*context*/, const ::taskservice::TaskRequest* /*request*/, ::grpc::ServerWriter< ::taskservice::TaskResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ExecuteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ExecuteTask() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ExecuteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTask(::grpc::ServerContext* /*context*/, const ::taskservice::TaskRequest* /*request*/, ::taskservice::TaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ExecuteTaskAsync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ExecuteTaskAsync() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ExecuteTaskAsync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTaskAsync(::grpc::ServerContext* /*context*/, const ::taskservice::TaskRequest* /*request*/, ::grpc::ServerWriter< ::taskservice::TaskResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteTaskAsync(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ExecuteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ExecuteTask() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ExecuteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTask(::grpc::ServerContext* /*context*/, const ::taskservice::TaskRequest* /*request*/, ::taskservice::TaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteTask(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ExecuteTaskAsync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ExecuteTaskAsync() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->ExecuteTaskAsync(context, request); }));
    }
    ~WithRawCallbackMethod_ExecuteTaskAsync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTaskAsync(::grpc::ServerContext* /*context*/, const ::taskservice::TaskRequest* /*request*/, ::grpc::ServerWriter< ::taskservice::TaskResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* ExecuteTaskAsync(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ExecuteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ExecuteTask() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ExecuteTask(context, request, response); }));
    }
    ~WithRawCallbackMethod_ExecuteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteTask(::grpc::ServerContext* /*context*/, const ::taskservice::TaskRequest* /*request*/, ::taskservice::TaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExecuteTask(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ExecuteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ExecuteTask() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::taskservice::TaskRequest, ::taskservice::TaskResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::taskservice::TaskRequest, ::taskservice::TaskResponse>* streamer) {
                       return this->StreamedExecuteTask(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ExecuteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ExecuteTask(::grpc::ServerContext* /*context*/, const ::taskservice::TaskRequest* /*request*/, ::taskservice::TaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedExecuteTask(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::taskservice::TaskRequest,::taskservice::TaskResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ExecuteTask<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_ExecuteTaskAsync : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_ExecuteTaskAsync() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::taskservice::TaskRequest, ::taskservice::TaskResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::taskservice::TaskRequest, ::taskservice::TaskResponse>* streamer) {
                       return this->StreamedExecuteTaskAsync(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_ExecuteTaskAsync() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ExecuteTaskAsync(::grpc::ServerContext* /*context*/, const ::taskservice::TaskRequest* /*request*/, ::grpc::ServerWriter< ::taskservice::TaskResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedExecuteTaskAsync(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::taskservice::TaskRequest,::taskservice::TaskResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_ExecuteTaskAsync<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_ExecuteTaskAsync<WithStreamedUnaryMethod_ExecuteTask<Service > > StreamedService;
};

}  // namespace taskservice


#endif  // GRPC_proto_2ftask_5fservice_2eproto__INCLUDED
